### ISSUE TITLE
Any Easy Way to Cover Other Halo Games?

### ISSUE THREAD

**Issue by attheshow** [mickelsonmichael/HaloCollectibles#43]
I'm interested in tracking other Halo games in the same way that you've done here. Is there any easy way to adjust the code to have it include other game ids?

**Comment by mickelsonmichael** [comment]
Somewhat easy, yes. But you'd be more or less creating your own website at that point

I've got an API hosted on Azure that is contacting some achievement APIs. All it does is pull down a list of the Master Chief Collection achievements, then grabs the ones for the specific game. To reproduce this for other games, you can simply create your own (free) endpoint on Azure or AWS (or GCP or Heroku, doesn't really matter) which calls for the game you are interested in instead. You could also create a nodejs server to make these requests, but I chose not to do that because then it wouldn't be freely hosted on GitHub Pages.

**Comment by attheshow** [comment]
Cool. It's an interesting project. I'm looking to move away from TrueAchievements personally and wanting to have something that I can run on my own to monitor my achievements. Obviously Xbox provides some tools but not any links to achievement guides on places like TrueAchievements, YouTube, etc. I'm also looking at possibly building something with OpenXBL. We'll see what I can come up with. Thanks! :)

**Comment by mickelsonmichael** [comment]
The OpenXBL API is pretty easy to use, so I highly recommend it. Once you have that in place then you just need to create a UI and you're on your way! Good luck

**Comment by attheshow** [comment]
I looked at that one but it doesn't look like it's well maintained and it also doesn't support legacy achievements for the 360. I'm experimenting today with this one: https://xapi.us/documentation. Having pretty good luck so far! :)

**Comment by mickelsonmichael** [comment]
I also utilize that one, but I recall preferring OpenXBL over it. I think the request limit for XAPI is much lower for the free tier than OpenXBL
